// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awssagemakerconnector.actions;

import java.util.Map;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import awsauthentication.impl.AuthCredentialsProvider;
import awsauthentication.impl.CredentialsProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.core.exception.SdkClientException;
import software.amazon.awssdk.core.exception.SdkServiceException;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.sagemakerruntime.SageMakerRuntimeClient;
import software.amazon.awssdk.services.sagemakerruntime.model.InvokeEndpointRequest;
import software.amazon.awssdk.services.sagemakerruntime.model.InvokeEndpointResponse;
import java.nio.charset.Charset;

public class SageMakerEndPoint_Paramaterise extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private java.lang.String Endpoint;
	private java.lang.String Region;

	public SageMakerEndPoint_Paramaterise(IContext context, IMendixObject Credentials, java.lang.String Endpoint, java.lang.String Region)
	{
		super(context);
		this.__Credentials = Credentials;
		this.Endpoint = Endpoint;
		this.Region = Region;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		// BEGIN USER CODE
		ILogNode LOGGER = Core.getLogger("SageMaker");
//		int attLength = members.size();
//		int count = 0;
//		Object[] inputArray = new Object [attLength];
//		members.values().forEach(v -> 
//			inputArray[count] = v.getValue(getContext());
//			count++);
//		
//		for (var entry : map.entrySet()) {
//		    System.out.println(entry.getKey() + "/" + entry.getValue());
//		}
		
        String payload = "";
        LOGGER.info(payload);
        String contentType = "application/list-text";
        
        
        

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SageMakerEndPoint_Paramaterise";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
